import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Logo from '../components/Logo'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Darija.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://darija.dev">Darija.dev</a>
        </h1>

        <div style={{width:'100%'}}>
          <Logo/>
        </div>
      </main>

      
    </div>
  )
}
